version: '2.3'

services:
  tiantang:
    image: ericwang2006/ttnode
    restart: always
    privileged: true
    networks:
      # 这里需要与下面 networks 中配置的网络设备名相同
      macvlan:
        # 指定一个在你的网络中有效且未被占用的IP地址
        ipv4_address: 192.168.1.223
    container_name: tiantang
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 指定要挂载为数据目录的本机位置
      - ./data:/mnts:rw

networks:
  # 这里修改为刚才创建的macvlan网络的名字
  macvlan:
    external: true
