version: '2.3'
services:
  baiduyun:
    image: kevinlad/baidunetdisk-docker:latest
    container_name: baiduyun
    restart: always
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    privileged: true
    environment:
      - "ENABLE_CJK_FONT:1"
      - "VNC_PASSWORD=123456"
      - "GROUP_ID:1000"
      - "USER_ID:1000"
    ports:
      - "5800:5800"
      - "5900:5900"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
